# Generated by Django 3.0.4 on 2020-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_customer',
            name='type_cus_caption',
            field=models.CharField(max_length=30, verbose_name='Тип заказчика'),
        ),
    ]
