# Generated by Django 3.0.4 on 2020-03-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200330_1754'),
        ('orders', '0004_auto_20200330_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Сustomer',
        ),
    ]
