# Generated by Django 3.0.4 on 2020-03-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='T_car',
        ),
        migrations.AddField(
            model_name='cars',
            name='Mark_caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car_mark', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='cars',
            name='Model_caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car_model', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='cars',
            name='Spec_caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car_specification', verbose_name='Спецификация'),
        ),
        migrations.AddField(
            model_name='cars',
            name='carrying',
            field=models.PositiveIntegerField(default=0, verbose_name='Грузоподъемность'),
        ),
        migrations.AddField(
            model_name='cars',
            name='rent',
            field=models.PositiveIntegerField(default=0, verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='expenses',
            field=models.PositiveIntegerField(default=0, verbose_name='Затраты'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='income',
            field=models.PositiveIntegerField(default=0, verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='profit',
            field=models.IntegerField(default=0, verbose_name='Прибыль'),
        ),
        migrations.DeleteModel(
            name='Type_car',
        ),
    ]
