# Generated by Django 3.0.4 on 2020-04-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_expenses_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='income',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='profit',
        ),
        migrations.AddField(
            model_name='expenses',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Cars', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='profit',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Cars', verbose_name='Автомобиль'),
        ),
    ]
