# Generated by Django 3.0.4 on 2020-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200401_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Mark_caption',
            field=models.CharField(max_length=30, null=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Model_caption',
            field=models.CharField(max_length=30, null=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Spec_caption',
            field=models.CharField(max_length=30, null=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='state_number',
            field=models.CharField(max_length=7, verbose_name='Гос номер'),
        ),
    ]
