# Generated by Django 3.0.4 on 2020-04-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200401_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Mark_caption',
            field=models.CharField(max_length=30, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Model_caption',
            field=models.CharField(max_length=30, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Spec_caption',
            field=models.CharField(max_length=30, null=True, verbose_name='Спецификация'),
        ),
    ]
