# Generated by Django 3.0.4 on 2020-04-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200401_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
