# Generated by Django 3.0.4 on 2020-03-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='position',
            name='position_caption',
            field=models.CharField(max_length=10, verbose_name='Наименование должности'),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='P_position',
        ),
        migrations.AddField(
            model_name='worker',
            name='P_position',
            field=models.ManyToManyField(to='workers.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='middle_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='passport',
            field=models.CharField(max_length=20, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
