# Generated by Django 3.0.4 on 2020-03-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20200315_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_caption',
            field=models.CharField(max_length=20, verbose_name='Наименование должности'),
        ),
    ]
