# Generated by Django 3.0.4 on 2020-03-21 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20200321_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='P_position',
        ),
        migrations.AddField(
            model_name='worker',
            name='P_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Position', verbose_name='Должность'),
        ),
    ]
