# Generated by Django 3.0.4 on 2020-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20200322_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='passport',
        ),
        migrations.AddField(
            model_name='worker',
            name='passport_date',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='worker',
            name='passport_issued',
            field=models.CharField(max_length=100, null=True, verbose_name='Паспорт выдан'),
        ),
        migrations.AddField(
            model_name='worker',
            name='passport_number',
            field=models.CharField(max_length=6, null=True, verbose_name='Номер Паспорта'),
        ),
        migrations.AddField(
            model_name='worker',
            name='passport_seria',
            field=models.CharField(max_length=4, null=True, verbose_name='Серия Паспорта'),
        ),
    ]
