# Generated by Django 3.0.4 on 2020-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20200407_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='type_work',
            field=models.CharField(choices=[('R', 'Repairs'), ('W', 'Working time')], default='W', max_length=1, null=True, verbose_name='Тип работы'),
        ),
    ]
