# Generated by Django 3.0.4 on 2020-04-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_worker_type_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=20, verbose_name='Наименование занятости')),
                ('salary', models.CharField(max_length=20, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.RemoveField(
            model_name='worker',
            name='type_work',
        ),
        migrations.AddField(
            model_name='worker',
            name='time',
            field=models.IntegerField(null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='worker',
            name='T_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Type_work', verbose_name='Тип работы'),
        ),
    ]
