# Generated by Django 3.0.4 on 2020-04-15 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20200414_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type_work',
            options={'verbose_name': 'Тип работы', 'verbose_name_plural': 'Типы работы'},
        ),
        migrations.CreateModel(
            name='Tabel_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0, null=True, verbose_name='Количество часов')),
                ('data', models.DateField(default=datetime.datetime(2020, 4, 15, 18, 2, 57, 570138, tzinfo=utc), null=True)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Worker', verbose_name='Сотрудник')),
            ],
        ),
    ]
