# Generated by Django 3.0.4 on 2020-04-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20200415_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabel_time',
            old_name='time',
            new_name='day1',
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day10',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day11',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day12',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day13',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day14',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day15',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day16',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day17',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day18',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day19',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day2',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day20',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day21',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day22',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day23',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day24',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day25',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day26',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day27',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day28',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day29',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day3',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day30',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day31',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day4',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day5',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day6',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day7',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day8',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='tabel_time',
            name='day9',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='tabel_time',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
