# Generated by Django 3.0.4 on 2020-05-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_auto_20200429_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='P_position',
        ),
    ]
