# Generated by Django 3.0.4 on 2020-05-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_remove_worker_p_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='P_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Position', verbose_name='Должность'),
        ),
    ]
