# Generated by Django 3.0.4 on 2020-05-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_worker_p_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='passport_number',
            field=models.CharField(max_length=6, verbose_name='Номер Паспорта'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='passport_seria',
            field=models.CharField(max_length=4, verbose_name='Серия Паспорта'),
        ),
    ]
