# Generated by Django 3.0.4 on 2020-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cus_caption', models.CharField(max_length=30, verbose_name='Тип заказчика')),
            ],
            options={
                'verbose_name': 'Тип заказчика',
                'verbose_name_plural': 'Типы заказчиков',
            },
        ),
        migrations.CreateModel(
            name='Сustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('organization', models.CharField(blank=True, max_length=20, null=True, verbose_name='Организация')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('T_customer', models.ManyToManyField(to='customers.Type_customer', verbose_name='Тип заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
    ]
