# Generated by Django 3.0.4 on 2020-03-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сustomer',
            name='T_customer',
        ),
        migrations.AddField(
            model_name='сustomer',
            name='T_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Type_customer', verbose_name='Тип заказчика'),
        ),
    ]
