# Generated by Django 3.0.4 on 2020-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200331_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сustomer',
            name='T_customer',
        ),
        migrations.AddField(
            model_name='сustomer',
            name='T_customer',
            field=models.ManyToManyField(default=1, to='customers.Type_customer', verbose_name='Тип заказчика'),
        ),
    ]
