# Generated by Django 3.0.4 on 2020-03-19 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('cars', '0001_initial'),
        ('workers', '0002_auto_20200315_1501'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('time', models.IntegerField(verbose_name='Время')),
                ('final_price', models.IntegerField(verbose_name='Итоговая стоимость')),
                ('adress', models.CharField(max_length=20, verbose_name='Адрес')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Cars', verbose_name='Количество')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Сustomer', verbose_name='Заказчик')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Product', verbose_name='Продукт')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
