# Generated by Django 3.0.4 on 2020-04-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200330_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('С', 'Сompleted'), ('D', 'During')], default='D', max_length=1, null=True, verbose_name='Статус'),
        ),
    ]
