# Generated by Django 3.0.4 on 2020-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
