# Generated by Django 3.0.4 on 2020-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200527_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=20, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
