# Generated by Django 3.0.4 on 2020-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200613_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
